Bahmni/bahmni-playbooks

roles/bahmni-reports/defaults/main.yml, roles/bahmni-reports/templates/bahmni-reports.properties.j2
Reverts Bahmni/bahmni-playbooks#10
=> Revert "Suman | BAH-567 | Modify bahmni-reports.properties.j2 to accommodate …"

roles/iptables/tasks/main.yml
https://bahmni.atlassian.net/browse/BAH-667
=> Shilpa|BAH-667|Replacing service with systemd in ansible 2.4 onwards

roles/bahmni-emr/tasks/main.yml, roles/iptables/tasks/main.yml, roles/mysql-replication/tasks/start_emr.yml
Replaced the deprecated always_run command with check_mode
=> BAH-680 : Remove always-run in bahmni-playbooks

roles/bahmni-emr/tasks/main.yml, roles/iptables/tasks/main.yml, roles/mysql-replication/tasks/start_emr.yml
Reverts Bahmni/bahmni-playbooks#23
=> Revert "BAH-680 : Remove always-run in bahmni-playbooks"

roles/iptables/tasks/main.yml
Added the task to install Iptables services
=> BAH-634 : Add  step in bahmni installation process for iptables services

roles/iptables/tasks/main.yml
Reverts Bahmni/bahmni-playbooks#20
=> Revert "BAH-634 : Add  step in bahmni installation process for iptables services"

roles/bahmni-web/templates/ssl.conf.j2
https://bahmni.atlassian.net/browse/BAH-632
=> Shilpa|BAH-632|Made httpd 2.4 service running

roles/bahmni-emr/tasks/main.yml, roles/iptables/tasks/main.yml, roles/mysql-replication/tasks/start_emr.yml
Replaced always_run with check_mode: no
=> BAH-680 | Remove always-run in bahmni-playbooks

dev/rpm_versions.yml, group_vars/dev, roles/bahmni-emr/tasks/main.yml, roles/bahmni-emr/templates/openmrs-runtime.properties.j2
https://bahmni.atlassian.net/browse/BAH-631
=> Shilpa|BAH-631|Bahmni-package merging of bahmni-openmrs into bahmni-emr

group_vars/dev, roles/bahmni-erp/defaults/main.yml, roles/bahmni-lab/defaults/main.yml
https://bahmni.atlassian.net/browse/BAH-633
=> Shilpa|BAH-633|Upgrading postgresql to 9.5

group_vars/dev, group_vars/local, roles/bahmni-erp/defaults/main.yml, roles/bahmni-lab/defaults/main.yml, roles/postgres/defaults/main.yml
https://bahmni.atlassian.net/browse/BAH-737
=> Shilpa|BAH-737|Upgrading PostgreSQL to 9.6

roles/mysql/tasks/main.yml
Upgrade Mysql for 5.6 to 5.7 migration 
JIRA link - https://bahmni.atlassian.net/browse/BAH-630
=> Rajashri| Upgrade Mysql and restart server for changes to take effect

group_vars/dev, group_vars/local, roles/bahmni-emr/defaults/main.yml, roles/installer-config/defaults/main.yml, roles/mysql-db-backup-incr/defaults/main.yml, roles/mysql-db-restore-incr/defaults/main.yml, roles/mysql-replication/defaults/main.yml, roles/mysql-users/defaults/main.yml, roles/mysql/defaults/main.yml, roles/mysql/files/mysql_secure_installation.sql
Passwords have to changed to satisfy the medium password policy
=> Password changes for MEDUIM policy

roles/bahmni-emr/tasks/main.yml
https://bahmni.atlassian.net/browse/BAH-680
=> Shilpa|BAH-680|Pushing changes again

roles/nagios/tasks/nagios.yml, roles/nagios/templates/nagios.cfg, roles/nagios/templates/templates.cfg
Initial commit/PR to test it out.
=> BAH-360 | Install nagios 4.x

incr-mysqldbbackup.yml, incr-mysqldbrestore.yml, roles/mysql-db-restore-incr/tasks/xtrabackuprestore.yml, roles/mysql-replication/tasks/main.yml, roles/mysql-replication/tasks/slave.yml, roles/mysql-replication/tasks/start_emr.yml, roles/mysql-replication/tasks/stop_emr.yml
https://bahmni.atlassian.net/browse/BAH-641
=> Shilpa|BAH-641|service to systemd in mysql related files

all.yml, roles/mysql/tasks/main.yml
https://bahmni.atlassian.net/browse/BAH-734
=> Shilpa|BAH-734|Password updating changes

group_vars/dev, group_vars/local, roles/bahmni-erp/defaults/main.yml, roles/bahmni-lab/defaults/main.yml, roles/bahmni-odoo/defaults/main.yml, roles/postgres/defaults/main.yml
Correcting the fix, to make the pgdg-redhat-repo-42.0-11.noarch.rpm version to be pulled and not latest
=> Buvana | BAH-1037 | Installing Bahmni 0.92 on my new CentOS 7 server fails - Postgres Issue.

all.yml, roles/bahmni-appointments-frontend/tasks/main.yml
https://bahmni.atlassian.net/browse/AP-75
=> Bindu | AP-75 | Add playbook role for appointments-frontend to install  hrough bahmni installer

roles/bahmni-odoo/tasks/main.yml
The downgraded version is 3.5.3 as it was the supported version w.r.t odoo 10.
=> BAH-1124|Buvaneswari|Odoo page distortion - lessc downgrade issue

roles/mysql/defaults/main.yml
=> BAH-1178|Buvaneswari|Defaulting mysql-5.6.48 as the version for 0.93 release

roles/postgres/defaults/main.yml
PR to fix Postgres 9.6 installation.
=> BAH-1496 - | Mradul | - Update for Postgres 9.6 support

roles/bahmni-web/templates/ssl.conf.j2, roles/httpd/templates/index.html.j2
Co-authored-by: stavtnameh <hemanth.v@beehyv.com>
=> BAH-1816 | Added tags for disabling search engine crawling

roles/bahmni-reports/templates/bahmni-reports.properties.j2
BAH-2131 | Report-generated-on time-is-incorrect-in-report
=> BAH-2131|Report-generated-on time-is-incorrect-in-report
